#!/usr/bin/env node
// scripts/build-skills.mjs — Round 9 #87.
import { promises as fs } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';

const CHECK = process.argv.includes('--check');

const SKILL_MAP = [
  { skill: 'meta-orchestration', sources: ['rules/role-charters.md'] },
  { skill: 'escalation-protocol', sources: ['rules/escalation.md'] },
  { skill: 'shared-state', sources: ['rules/communication-protocol.md'] },
];

function sha256(s) { return createHash('sha256').update(s).digest('hex').slice(0, 16); }

async function buildOne({ skill, sources }) {
  let combined = '';
  for (const s of sources) {
    try { combined += `\n<!-- mirror: ${s} -->\n` + await fs.readFile(s, 'utf8'); }
    catch {}
  }
  const hash = sha256(combined);
  const dest = join('skills', skill, 'SKILL.md');
  let existing = '';
  try { existing = await fs.readFile(dest, 'utf8'); } catch {}
  const existingHash = existing.match(/<!-- sources_sha:\s*([a-f0-9]+) -->/)?.[1];
  if (existingHash === hash) return { skill, status: 'unchanged' };
  if (CHECK) return { skill, status: 'drift', expected: hash, actual: existingHash };

  const content = `# Skill: ${skill}\n\n<!-- sources_sha: ${hash} -->\n<!-- AUTO-GENERATED by scripts/build-skills.mjs from: ${sources.join(', ')} -->\n${combined}\n`;
  await fs.mkdir(join('skills', skill), { recursive: true });
  await fs.writeFile(dest, content);
  return { skill, status: 'written' };
}

async function main() {
  const results = await Promise.all(SKILL_MAP.map(buildOne));
  let exit = 0;
  for (const r of results) {
    console.log(`[build-skills] ${r.skill}: ${r.status}`);
    if (CHECK && r.status === 'drift') exit = 1;
  }
  process.exit(exit);
}

main().catch((e) => { console.error(e.stack); process.exit(1); });
